version: "3.9"
services:
  front:
    build: front/.
    image: cz0r3k/counter_web_app:front
    depends_on:
      - api
  api:
    build: api/.
    image: cz0r3k/counter_web_app:api
    depends_on:
      - database
  database:
    image: redis
    volumes:
      - ./data:/data
  proxy:
    build: proxy/.
    image: cz0r3k/counter_web_app:proxy
    ports:
      - "80:80"
    depends_on:
      - front
