version: "3.9"
services:
  front:
    build: front/.
    image: rust_microservices_front
    depends_on:
      - api
  api:
    build: api/.
    image: rust_microservices_api
    depends_on:
      - database
  database:
    image: redis
    volumes:
      - ./data:/data
  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - front
  