version: "3.9"
services:
  front:
    build: front/.
    image: rust_microservices_front
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app_network
  api:
    build: api/.
    image: rust_microservices_api
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - app_network
  database:
    image: redis
    volumes:
      - ./data:/data
    networks:
      - app_network
networks:
  app_network: